[package]
name = "path-edit"
version = "0.1.0"
authors = ["Lion Ackermann <ackerm.lion@hotmail.de>"]
edition = "2018"
license = "MIT"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.5.1"
